DROP TABLE IF EXISTS user;
CREATE TABLE user (id SERIAL PRIMARY KEY, name VARCHAR(255), username VARCHAR(255), email VARCHAR(255));

DROP TABLE IF EXISTS post;
CREATE TABLE post (id SERIAL PRIMARY KEY, user_id NUMBER, title VARCHAR(255), body VARCHAR(255));

